CREATE TABLE "wishing_wealth_prices_daily" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "wishing_wealth_prices_daily_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"symbolId" bigint NOT NULL,
	"date" date NOT NULL,
	"open" numeric(20, 8),
	"close" numeric(20, 8),
	"adjClose" numeric(20, 8),
	"volume" bigint,
	"source" text DEFAULT 'tradingview' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "wishing_wealth_sessions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"userId" uuid NOT NULL,
	"issuedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"expiresAt" timestamp with time zone NOT NULL,
	"revokedAt" timestamp with time zone,
	"userAgent" text,
	"ip" "inet"
);
--> statement-breakpoint
CREATE TABLE "wishing_wealth_symbols" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "wishing_wealth_symbols_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"ticker" "citext" NOT NULL,
	"exchange" text NOT NULL,
	"isOnPage" boolean DEFAULT false NOT NULL,
	"firstSeen" date DEFAULT CURRENT_DATE,
	"lastSeen" date DEFAULT CURRENT_DATE
);
--> statement-breakpoint
CREATE TABLE "wishing_wealth_users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"email" "citext" NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
ALTER TABLE "wishing_wealth_prices_daily" ADD CONSTRAINT "prices_daily_symbol_id_symbols_id_fk" FOREIGN KEY ("symbolId") REFERENCES "public"."wishing_wealth_symbols"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "wishing_wealth_sessions" ADD CONSTRAINT "sessions_user_id_users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."wishing_wealth_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "prices_daily_symbol_date_key" ON "wishing_wealth_prices_daily" USING btree ("symbolId","date");--> statement-breakpoint
CREATE INDEX "prices_daily_symbol_date_desc_idx" ON "wishing_wealth_prices_daily" USING btree ("symbolId","date");--> statement-breakpoint
CREATE INDEX "sessions_active_idx" ON "wishing_wealth_sessions" USING btree ("userId","expiresAt") WHERE "wishing_wealth_sessions"."revokedAt" IS NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "symbols_ticker_exchange_key" ON "wishing_wealth_symbols" USING btree ("ticker","exchange");--> statement-breakpoint
CREATE INDEX "symbols_ticker_idx" ON "wishing_wealth_symbols" USING btree ("ticker");--> statement-breakpoint
CREATE INDEX "symbols_on_page_idx" ON "wishing_wealth_symbols" USING btree ("isOnPage");--> statement-breakpoint
CREATE UNIQUE INDEX "users_email_unique" ON "wishing_wealth_users" USING btree ("email");